### ISSUE TITLE
RM with mailer block syntax leads to errors (symbolize keys)

### ISSUE THREAD

**Issue by jogaco** [zapnap/resque_mailer#95] opened 2016-10-13 09:32 UTC
I only need to send a simple message without any template.
My class:

```
class Notifier < ActionMailer::Base
  include Resque::Mailer

  def send_simple_message(options)
    mail(options.except(:body)) do |format|
      format.text { render :plain => options[:body] }
    end
  end
end
```

`Notifier.send_simple_message(:from => 'info@example.com', :to => 'dest@example.com', :subject => 'Test', :body => "This is a test").deliver`
produces this:

> Subject: Send Simple Message
> Body: <empty>
> 
> 

By removing Resque:Mailer, I obtain this:

> Subject: Test
> Body: This is a test

**Comment by zapnap** [comment] 2016-10-13 14:31
Some more info would be helpful here. Version of Rails? Version of ResqueMailer? Version of Resque? Can you provide a simple sample Rails project that illustrates the problem?

**Comment by jogaco** [comment] 2016-10-13 19:51
Rails 4.2.4
Resque-Mail: 2.4.0
Resque: 1.25.2

**Comment by jogaco** [comment] 2016-10-13 20:19
Just do a `rails new mytest`,
add the `Notifier` class,
set `config.action_mailer.smtp_settings`

I just did this and was able to reproduce the problem

**Comment by zapnap** [comment] 2016-10-13 20:21
I’ll take a look at this later tonight. Can you try the 2.3.x gem in the
meantime?

On October 13, 2016 at 4:19:11 PM, J. Garcia (notifications@github.com)
wrote:

Just do a rails new mytest,
add the Notifier class,
set config.action_mailer.smtp_settings

I just did this and was able to reproduce the problem

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zapnap/resque_mailer/issues/95#issuecomment-253626991>,
or mute the thread

**Comment by jogaco** [comment] 2016-10-13 20:23
I was using 2.3.x and upgraded to the latest hoping it would work

**Comment by zapnap** [comment] 2016-10-13 20:24
So, just to be clear, you’re having problems with both 2.3.1 and 2.4.0?


On October 13, 2016 at 4:23:20 PM, J. Garcia (notifications@github.com)
wrote:

I was using 2.3.x and upgraded to the latest hoping it would work

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zapnap/resque_mailer/issues/95#issuecomment-253627961>,
or mute the thread

**Comment by zapnap** [comment] 2016-10-13 20:37
Just pushed the sample project I use to test this out locally here. Can't seem to replicate your issue. Try it out and modify to suit your environment, isolate the issue?

https://github.com/zapnap/resque_mailer_test

**Comment by jogaco** [comment] 2016-10-13 20:43
Ok. Will check and report back
El dia 13/10/2016 22.37, "Nick Plante" <notifications@github.com> va
escriure:

**Comment by jogaco** [comment] 2016-10-14 10:57
Your test project works fine.
However, I was using a documented way of sending plain emails.
While debugging, I caught the culprit of it:

```
mail(options.except(:body)) do |format|
    format.text { render :plain => options[:body] }
end
```
When this block is run, options is a hash with values:
Hash (4 elements)
'from' => info@example.com
'to' => dest@example.com
'subject' => Test
'body' => This is a test

Notice the keys are strings, not symbols!

Then this method does not determine the template properly:

```
    def determine_template(options)
      keys = options.has_key?(:locals) ? options[:locals].keys : []

      if options.key?(:body)
        Template::Text.new(options[:body])
      elsif options.key?(:text)
        Template::Text.new(options[:text], formats.first)
      elsif options.key?(:plain)
        Template::Text.new(options[:plain])
      elsif options.key?(:html)
        Template::HTML.new(options[:html], formats.first)
      elsif options.key?(:file)
        with_fallbacks { find_file(options[:file], nil, false, keys, @details) }
      elsif options.key?(:inline)
        handler = Template.handler_for_extension(options[:type] || "erb")
        Template.new(options[:inline], "inline template", handler, :locals => keys)
      elsif options.key?(:template)
        if options[:template].respond_to?(:render)
          options[:template]
        else
          find_template(options[:template], options[:prefixes], false, keys, @details)
        end
      else
        raise ArgumentError, "You invoked render but did not give any of :partial, :template, :inline, :file, :plain, :text or :body option."
      end
    end
```

Because `options[:key]` is `nil`

**Comment by jogaco** [comment] 2016-10-14 11:12
I would suggest to pre-process serialized args and convert hash keys into symbols, so code from Rails library is not broken

**Comment by zapnap** [comment] 2016-10-14 14:15
Strange that no one else has ever had an issue! I assume you're using the default RM serializer (pass-thru). I'll take a look at this when I have a chance; unfortunately I'm a bit behind on other tasks atm. Pull requests are, of course, always welcome ;-). In the meantime changing the name of this issue so it more accurately reflects the problem you're reporting.

**Comment by zapnap** [comment] 2016-10-18 13:58
Fixed in https://github.com/zapnap/resque_mailer/commit/3feb4a462892a8a3520420caded63443fe9f0f28

**Closed** 2016-10-18 13:57 UTC
